AEFrame
NAME
AEFrame - This module is the engine's precise frame/loop-cycle limiter.
SYNOPSIS
#include <AEFrame.hpp>
Inherits __AEModuleBase< AEFrame >.
Public Types
using AEFrameClock = AEF_CLOCK
This is an an alias for the internal clock of the AEFrame module.
Public Member Functions
AEFrame (const double fps=ENGINE_FPS) noexcept
Class constructor -- constructs the instance with the fps as the delay.
AEFrame (const AEFrame &two) noexcept
Copy constructor -- copies data from a passed AEFrame instance.
AEFrame & operator= (const AEFrame &two) noexcept
Copy-assignment operator -- copies data from a passed AEFrame instance
void setFps (const double fps) noexcept
Sets the delay of the instance as the frames (loop cycles) per second to reach in execution (fps goal).
void sleep (void) noexcept
Puts the current thread to sleep for the delay that was set earlier.
void resetTimePoint (void) noexcept
Resets the time point in the AEFrame to the real (current) time.
double getFPS (void) const noexcept
Returns the fps goal of the instance.
double getDelay (void) const noexcept
Returns the maximum loop delay in the instance in seconds.
bool hasDelay (void) const noexcept
Returns whether the instance has a delay or not (invalid fps/delay was set).
constexpr const ullint getModuleID (void) noexcept
Get the id number of the instance of the module.
Static Public Member Functions
static constexpr bool isValidFPS (const double fps) noexcept
Returns whether the passed delay as fps is valid.
static constexpr bool isValidDelay (const double sec) noexcept
Returns whether the passed delay as seconds is valid.
static ullint getModuleAmount (void) noexcept
Get the amount of the currently-alive instances of module T.
static constexpr const std::string_view getModuleName (void) noexcept
Get the name of the module.
static constexpr const ullint getInstanceCounter (void) noexcept
Get the current value of the instance counter of the module.
Protected Attributes
const ullint m_ullModuleId
The ID number of the current module.
Static Protected Attributes
static std::atomic< std::size_t > m_ullModulesAlive
Amount of the currently-alive (not destroyed) instances of the module.
static std::atomic< ullint > m_ullInstanceCounter
Amount of the instances of the module ever created during the program's runtime.
Private Member Functions
REGISTER_MODULE (AEFrame)
The instantiation of necessary functions from __AEModuleBase class.
Private Attributes
timeDur< double > m_tdChronoDelay
The time duration for the sleeping delay
timePoint< AEFrameClock, decltype(m_tdChronoDelay)> m_tpTimepoint
The timepoint, that sets time when to wake up the thread.
double m_fFPS
bool m_bNoDelay
The flag if we don't need the delay, err, for some reason.
Static Private Attributes
static constexpr timeDur< double > m_tdResetTime = microSec(milliSec(llint(100)))
The time duration for resetting the AEFrame::m_tpTimepoint if it gets too different with real time.
Detailed Description
This module is the engine's precise frame/loop-cycle limiter.
It allows to limit the execution of a loop to a set amount of iterations per second.
 Or, instead have the set delay per each loop cycle.
It works by sleeping the difference between the time spent by code in the loop and the time per each frame.
For example:
 If you want the loop to have 100 cycles/second or fps (10 milliseconds per cycle), and the code takes 4ms to complete, then the AEFrame will sleep the difference.
 In this case it's 6ms to make it up to the 10ms per cycle.
Note
By default it uses the value of ENGINE_FPS as the fps target for the loops
This isn't multithreading safe.
Definition at line 53 of file AEFrame.hpp.
Member Typedef Documentation
using AEFrame::AEFrameClock = AEF_CLOCK
This is an an alias for the internal clock of the AEFrame module.
Warning
The resulution of the AEFrameClock that your compiler gives must be at least 1 microsecond, otherwise it won't compile (breaks assertion).
Definition at line 60 of file AEFrame.hpp.
Constructor & Destructor Documentation
AEFrame::AEFrame (const double fps = ENGINE_FPS) [inline], [explicit], [noexcept]
Class constructor -- constructs the instance with the fps as the delay.
See also
AEFrame::setFPS()
Attention
If you pass the invalid fps value, it will disable the delay (sets AEFrame::m_bNoDelay to true); Setting it to a valid value enables it back.
See also
AEFrame::isValidFPS()
Note
Defaults the fps delay to ENGINE_FPS
Parameters
fps The fps goal that the frame delay module will try to achieve
Definition at line 73 of file AEFrame.hpp.
AEFrame::AEFrame (const AEFrame & two) [inline], [noexcept]
Copy constructor -- copies data from a passed AEFrame instance.
Parameters
two The second AEFrame instance
Definition at line 82 of file AEFrame.hpp.
Member Function Documentation
AEFrame & AEFrame::operator= (const AEFrame & two) [inline], [noexcept]
Copy-assignment operator -- copies data from a passed AEFrame instance
Note
This resets the internal time point (calls AEFrame::resetTimePoint())
Parameters
two The second AEFrame instance
Returns
The reference to the resulting AEFrame instance.
Definition at line 97 of file AEFrame.hpp.
References m_bNoDelay, m_fFPS, m_tdChronoDelay, m_tpTimepoint, and resetTimePoint().
void AEFrame::setFps (const double fps) [inline], [noexcept]
Sets the delay of the instance as the frames (loop cycles) per second to reach in execution (fps goal).
Attention
If you pass the invalid fps value, it will disable the delay (sets AEFrame::m_bNoDelay to true); Setting it to a valid value enables it back.
See also
AEFrame::isValidFPS()
Note
This resets the internal time point (calls AEFrame::resetTimePoint())
Parameters
fps The frames(cycles) per second to set the delay as
Definition at line 118 of file AEFrame.hpp.
References isValidFPS(), m_bNoDelay, m_fFPS, m_tdChronoDelay, and m_tpTimepoint.
void AEFrame::sleep (void) [inline], [noexcept]
Puts the current thread to sleep for the delay that was set earlier. Example: if the fps delay was set to 30fps (~~33ms delay in real time) and a game loop takes just 13ms, then the thread will sleep the rest of 20ms to make the game loop run at around ~~33ms of delay or around 30fps.
Attention
If the delay is disabled (AEFrame::m_bNoDelay is true), just returns and doesn't do anything
Note
If the AEFrame::m_tpTimepoint gets too out of touch with real time, resets the time point (calls AEFrame::resetTimePoint()) The definition of 'out of touch' is controlled by AEF_RESET_TIME_WHEN_BEHIND_MS.
Automatic timepoint resetting works only if AEF_RESET_TIME_WHEN_BEHIND_MS is enabled
Definition at line 154 of file AEFrame.hpp.
References m_bNoDelay, m_tdChronoDelay, m_tdResetTime, m_tpTimepoint, resetTimePoint(), and sleepUntil.
void AEFrame::resetTimePoint (void) [inline], [noexcept]
Resets the time point in the AEFrame to the real (current) time. Helps if the AEFrame::m_tpTimepoint time point drifted far from the reality.
Definition at line 175 of file AEFrame.hpp.
References m_tpTimepoint.
double AEFrame::getFPS (void) const [inline], [noexcept]
Returns the fps goal of the instance.
Returns
The fps goal of the instance as type double.
Definition at line 185 of file AEFrame.hpp.
References m_fFPS.
double AEFrame::getDelay (void) const [inline], [noexcept]
Returns the maximum loop delay in the instance in seconds. Or better: the time, in seconds, for each loop cycle that AEFrame::sleep() is called
Returns
The delay of the instance as seconds as type double.
Definition at line 197 of file AEFrame.hpp.
References m_tdChronoDelay.
bool AEFrame::hasDelay (void) const [inline], [noexcept]
Returns whether the instance has a delay or not (invalid fps/delay was set).
See also
AEFrame::isValidDelay()
Returns
If the instance has delay enabled (valid fps/delay):
True
If the instance has delay disabled (invalid fps/delay):
False
Definition at line 213 of file AEFrame.hpp.
References m_bNoDelay.
static constexpr bool AEFrame::isValidFPS (const double fps) [inline], [static], [constexpr], [noexcept]
Returns whether the passed delay as fps is valid.
Parameters
fps The frames per second value to check
Returns
If the fps value is valid -- more than 0 and less than/equal to 1 million:
True
Otherwise:
False
Definition at line 228 of file AEFrame.hpp.
static constexpr bool AEFrame::isValidDelay (const double sec) [inline], [static], [constexpr], [noexcept]
Returns whether the passed delay as seconds is valid.
Parameters
fps The frames per second value to check
Returns
If the delay value is valid -- more than 0 and less than int32_t max (2^31 - 1):
True
Otherwise:
False
Definition at line 243 of file AEFrame.hpp.
AEFrame::REGISTER_MODULE (AEFrame) [private]
The instantiation of necessary functions from __AEModuleBase class. This is things like module names, etc.
Warning
This is NOT a function of this class. Instead it's a macro call to the REGISTER_MODULE() in the AEModuleBase.hpp.
static ullint __AEModuleBase< AEFrame >::getModuleAmount (void) [inline], [static], [noexcept], [inherited]
Get the amount of the currently-alive instances of module T.
See also
__AEModuleBase<T>::m_ullModulesAlive
Returns
Unsigned long long of the alive module amount
Definition at line 122 of file AEModuleBase.hpp.
static constexpr const std::string_view __AEModuleBase< AEFrame >::getModuleName (void) [static], [constexpr], [noexcept], [inherited]
Get the name of the module.
Attention
You need to add REGISTER_MODULE() to the end of the class declarations if you want to use this thing
See also
REGISTER_MODULE()
Returns
The name of the module as a const std::strinv_view type
constexpr const ullint __AEModuleBase< AEFrame >::getModuleID (void) [inline], [constexpr], [noexcept], [inherited]
Get the id number of the instance of the module.
Remarks
Every module has its own instance counter
Returns
The id number of the instance of the module as ullint type
Definition at line 145 of file AEModuleBase.hpp.
static constexpr const ullint __AEModuleBase< AEFrame >::getInstanceCounter (void) [inline], [static], [constexpr], [noexcept], [inherited]
Get the current value of the instance counter of the module.
See also
__AEModuleBase::m_ullInstanceCounter
Returns
The amount of the module's instances overall created throughout the program's runtime
Definition at line 157 of file AEModuleBase.hpp.
Member Data Documentation
constexpr timeDur<double> AEFrame::m_tdResetTime = microSec(milliSec(llint(100))) [static], [constexpr], [private]
The time duration for resetting the AEFrame::m_tpTimepoint if it gets too different with real time. Only exists if AEF_RESET_TIME_WHEN_BEHIND_MS is defined
See also
AEF_RESET_TIME_WHEN_BEHIND_MS
Definition at line 259 of file AEFrame.hpp.
timeDur<double> AEFrame::m_tdChronoDelay [private]
The time duration for the sleeping delay
Definition at line 263 of file AEFrame.hpp.
timePoint<AEFrameClock, decltype(m_tdChronoDelay)> AEFrame::m_tpTimepoint [private]
The timepoint, that sets time when to wake up the thread.
Definition at line 265 of file AEFrame.hpp.
double AEFrame::m_fFPS [private]
Definition at line 266 of file AEFrame.hpp.
bool AEFrame::m_bNoDelay [private]
The flag if we don't need the delay, err, for some reason.
Definition at line 268 of file AEFrame.hpp.
std::atomic<std::size_t> __AEModuleBase< AEFrame >::m_ullModulesAlive [inline], [static], [protected], [inherited]
Amount of the currently-alive (not destroyed) instances of the module.
Definition at line 166 of file AEModuleBase.hpp.
std::atomic<ullint> __AEModuleBase< AEFrame >::m_ullInstanceCounter [inline], [static], [protected], [inherited]
Amount of the instances of the module ever created during the program's runtime.
Definition at line 171 of file AEModuleBase.hpp.
const ullint __AEModuleBase< AEFrame >::m_ullModuleId [protected], [inherited]
The ID number of the current module.
Definition at line 176 of file AEModuleBase.hpp.
Author
Generated automatically by Doxygen for ArtyK's Console Engine from the source code.