AETimer
NAME
AETimer - This module is the engine's tick timer.
SYNOPSIS
#include <AETimer.hpp>
Inherits __AEModuleBase< AETimer >.
Public Member Functions
AETimer (const double tps)
Class constructor -- sets the delay in ticks per second, and starts the thread.
AETimer (void) noexcept
Class constructor -- assigns default delay (ENGINE_FPS) and doesn't start the thread.
AETimer (const AETimer &tm)
Copy constructor -- copies the data and, if the original timer was started, starts the timer.
AETimer & operator= (const AETimer &tm)
Copy assignment operator -- copies the data and, if the original timer was started, starts the timer.
~AETimer (void)
Class destructor
void startThread (void)
Starts the timer thread and starts tick counting.
void stopThread (void)
Stops the timer thread and stops tick counting.
void setTick (const ullint tick) noexcept
Sets the timer's new tick value to the passed value.
void resetTick (void) noexcept
Sets the timer tick back to 0.
void setTPS (const double tps, const cint flags=0)
Sets the timer's new delay as ticks-per-second.
bool isTicking (void) const noexcept
Checks whether the timer is ticking and the thread is running.
ullint getTick (void) const noexcept
Returns the current tick of the timer.
long double getWorldTime (void) const noexcept
Calculates the approximate world time of the timer's ticks as seconds.
double getTPS (void) const noexcept
Returns the ticks-per-second of the AETimer's instance (aka AEFrame's fps goal).
double getDelay (void) const noexcept
Returns the delay-per-tick of the instance, as seconds (aka AEFrame's delay).
constexpr const ullint getModuleID (void) noexcept
Get the id number of the instance of the module.
Static Public Member Functions
static void waitForTick (const AETimer &timer, const ullint tick) noexcept
Stops and sleeps the thread untill the given timer hits the certain tick number.
static void waitTicks (const AETimer &timer, const ullint tick) noexcept
Stops and sleeps the thread untill the given timer goes through certain amount of ticks.
static ullint getModuleAmount (void) noexcept
Get the amount of the currently-alive instances of module T.
static constexpr const std::string_view getModuleName (void) noexcept
Get the name of the module.
static constexpr const ullint getInstanceCounter (void) noexcept
Get the current value of the instance counter of the module.
Protected Attributes
const ullint m_ullModuleId
The ID number of the current module.
Static Protected Attributes
static std::atomic< std::size_t > m_ullModulesAlive
Amount of the currently-alive (not destroyed) instances of the module.
static std::atomic< ullint > m_ullInstanceCounter
Amount of the instances of the module ever created during the program's runtime.
Private Member Functions
void tickTimer (void) noexcept
The function that does the tick counting for the timer.
REGISTER_MODULE (AETimer)
The instantiation of necessary functions from __AEModuleBase class.
Private Attributes
AEFrame m_rDelay
The frame-rater of the timer for proper delay in the tick-counting function loop.
std::thread m_trdCounting
The thread object to launch the thread for the tick counting.
std::mutex m_mtxThreadMutex
The mutex to syncronise changes with the AETimer::m_rDelay when we're touching that.
std::atomic< ullint > m_ullTicks
The tick counter variable.
std::atomic< bool > m_bRunTrd
The flag to continue the loop for tick counting.
Detailed Description
This module is the engine's tick timer.
It allows to time or predict events ('happen at tick X'), with the variable tick speed.
 Internally it uses the AEFrame module for the delay, so the same limitations apply.
Internally it makes a separate thread that increments the tick number every set time period, and sleeping after.
See also
AEFrame
Note
This is multithreading-safe! :D
Definition at line 63 of file AETimer.hpp.
Constructor & Destructor Documentation
AETimer::AETimer (const double tps) [inline], [explicit]
Class constructor -- sets the delay in ticks per second, and starts the thread.
Parameters
tps The amount of ticks per second, as the double
Definition at line 72 of file AETimer.hpp.
References startThread().
AETimer::AETimer (void) [inline], [noexcept]
Class constructor -- assigns default delay (ENGINE_FPS) and doesn't start the thread.
Definition at line 80 of file AETimer.hpp.
AETimer::AETimer (const AETimer & tm) [inline]
Copy constructor -- copies the data and, if the original timer was started, starts the timer.
Parameters
tm The original AETimer instance to make a copy of
Definition at line 88 of file AETimer.hpp.
References m_bRunTrd, and startThread().
AETimer::~AETimer (void) [inline]
Class destructor
Definition at line 115 of file AETimer.hpp.
References stopThread().
Member Function Documentation
AETimer & AETimer::operator= (const AETimer & tm) [inline]
Copy assignment operator -- copies the data and, if the original timer was started, starts the timer.
Parameters
tm The original AETimer instance to make a copy of
Returns
Reference to the resulting AETimer copy
Definition at line 102 of file AETimer.hpp.
References m_bRunTrd, m_rDelay, m_ullTicks, startThread(), and stopThread().
void AETimer::startThread (void) [inline]
Starts the timer thread and starts tick counting.
Note
Does nothing if thread is already started
Does nothing if the previously-set delay/fps is invalid.
See also
AEFrame::isValidFPS()
AEFrame::isValidDelay()
AEFrame::hasDelay()
Definition at line 128 of file AETimer.hpp.
References AEFrame::hasDelay(), m_bRunTrd, m_rDelay, m_trdCounting, and tickTimer().
void AETimer::stopThread (void) [inline]
Stops the timer thread and stops tick counting.
Note
Does nothing if the thread was already stopped.
Definition at line 148 of file AETimer.hpp.
References m_bRunTrd, and m_trdCounting.
void AETimer::setTick (const ullint tick) [inline], [noexcept]
Sets the timer's new tick value to the passed value.
Parameters
tick The tick value to set instance's tick value to
Definition at line 160 of file AETimer.hpp.
References m_ullTicks.
void AETimer::resetTick (void) [inline], [noexcept]
Sets the timer tick back to 0.
Definition at line 167 of file AETimer.hpp.
References setTick().
void AETimer::setTPS (const double tps, const cint flags = 0) [inline]
Sets the timer's new delay as ticks-per-second.
Attention
If the value invalid, stops the thread.
See also
AEFrame::isValidFPS()
Note
Uses a mutex, so there could be some delay. Check the mutex behaviour on your system.
Parameters
tps The amount of ticks per second to set the delay to
flags The flag to indicate actions after setting the fps:
0 -- does nothing
1 -- reset the tick amount after changing the ticks-per-second value
2 -- approximately scale the tick counter to try to keep the world-time consistent; Uses the method of rounding indicated by AETM_TICK_ROUNDING_METHOD
Attention
If the previously-set delay/fps was invalid, it resets the tick value to 0, regardless of the passed flags value.
Definition at line 188 of file AETimer.hpp.
References _AETM_TICK_ROUND, getTPS(), AEFrame::hasDelay(), AEFrame::isValidFPS(), m_mtxThreadMutex, m_rDelay, m_ullTicks, resetTick(), AEFrame::setFps(), and stopThread().
bool AETimer::isTicking (void) const [inline], [noexcept]
Checks whether the timer is ticking and the thread is running.
Returns
If the thread was started/is running:
True
Otherwise:
False
Definition at line 218 of file AETimer.hpp.
References m_bRunTrd.
ullint AETimer::getTick (void) const [inline], [noexcept]
Returns the current tick of the timer.
Note
If thread is not started/working, the return value will be the same (duh)
Returns
Current timer tick as ullint type.
Definition at line 233 of file AETimer.hpp.
References m_ullTicks.
long double AETimer::getWorldTime (void) const [inline], [noexcept]
Calculates the approximate world time of the timer's ticks as seconds.
Note
If thread is not started/working, the return value will be the same (duh)
Returns
The approximation of the counted world time in seconds using the timer's ticks, as the double type.
Definition at line 245 of file AETimer.hpp.
References AEFrame::getDelay(), m_rDelay, and m_ullTicks.
double AETimer::getTPS (void) const [inline], [noexcept]
Returns the ticks-per-second of the AETimer's instance (aka AEFrame's fps goal).
See also
AEFrame::getFPS()
Returns
The ticks-per-second rate of the instance as double type.
Definition at line 257 of file AETimer.hpp.
References AEFrame::getFPS(), and m_rDelay.
double AETimer::getDelay (void) const [inline], [noexcept]
Returns the delay-per-tick of the instance, as seconds (aka AEFrame's delay).
See also
AEFrame::getDelay()
Returns
Delay-per-tick of the instance as seconds, as the double type.
Definition at line 269 of file AETimer.hpp.
References AEFrame::getDelay(), and m_rDelay.
static void AETimer::waitForTick (const AETimer & timer, const ullint tick) [inline], [static], [noexcept]
Stops and sleeps the thread untill the given timer hits the certain tick number.
Parameters
timer The instance of the AETimer to wait for
tick The AETimer instance tick value to wait for
Definition at line 279 of file AETimer.hpp.
References AEFrame::sleep().
static void AETimer::waitTicks (const AETimer & timer, const ullint tick) [inline], [static], [noexcept]
Stops and sleeps the thread untill the given timer goes through certain amount of ticks.
Parameters
timer The instance of the AETimer to wait for
tick The amount of ticks to wait for in the AETimer instance
Definition at line 292 of file AETimer.hpp.
References waitForTick().
void AETimer::tickTimer (void) [inline], [private], [noexcept]
The function that does the tick counting for the timer.
Definition at line 302 of file AETimer.hpp.
References m_bRunTrd, m_rDelay, m_ullTicks, and AEFrame::sleep().
AETimer::REGISTER_MODULE (AETimer) [private]
The instantiation of necessary functions from __AEModuleBase class. This is things like module names, etc.
Warning
This is NOT a function of this class. Instead it's a macro call to the REGISTER_MODULE() in the AEModuleBase.hpp.
static ullint __AEModuleBase< AETimer >::getModuleAmount (void) [inline], [static], [noexcept], [inherited]
Get the amount of the currently-alive instances of module T.
See also
__AEModuleBase<T>::m_ullModulesAlive
Returns
Unsigned long long of the alive module amount
Definition at line 122 of file AEModuleBase.hpp.
static constexpr const std::string_view __AEModuleBase< AETimer >::getModuleName (void) [static], [constexpr], [noexcept], [inherited]
Get the name of the module.
Attention
You need to add REGISTER_MODULE() to the end of the class declarations if you want to use this thing
See also
REGISTER_MODULE()
Returns
The name of the module as a const std::strinv_view type
constexpr const ullint __AEModuleBase< AETimer >::getModuleID (void) [inline], [constexpr], [noexcept], [inherited]
Get the id number of the instance of the module.
Remarks
Every module has its own instance counter
Returns
The id number of the instance of the module as ullint type
Definition at line 145 of file AEModuleBase.hpp.
static constexpr const ullint __AEModuleBase< AETimer >::getInstanceCounter (void) [inline], [static], [constexpr], [noexcept], [inherited]
Get the current value of the instance counter of the module.
See also
__AEModuleBase::m_ullInstanceCounter
Returns
The amount of the module's instances overall created throughout the program's runtime
Definition at line 157 of file AEModuleBase.hpp.
Member Data Documentation
AEFrame AETimer::m_rDelay [private]
The frame-rater of the timer for proper delay in the tick-counting function loop.
See also
AETimer::tickTimer()
Definition at line 314 of file AETimer.hpp.
std::thread AETimer::m_trdCounting [private]
The thread object to launch the thread for the tick counting.
Definition at line 316 of file AETimer.hpp.
std::mutex AETimer::m_mtxThreadMutex [private]
The mutex to syncronise changes with the AETimer::m_rDelay when we're touching that.
Definition at line 318 of file AETimer.hpp.
std::atomic<ullint> AETimer::m_ullTicks [private]
The tick counter variable.
Definition at line 320 of file AETimer.hpp.
std::atomic<bool> AETimer::m_bRunTrd [private]
The flag to continue the loop for tick counting.
Definition at line 322 of file AETimer.hpp.
std::atomic<std::size_t> __AEModuleBase< AETimer >::m_ullModulesAlive [inline], [static], [protected], [inherited]
Amount of the currently-alive (not destroyed) instances of the module.
Definition at line 166 of file AEModuleBase.hpp.
std::atomic<ullint> __AEModuleBase< AETimer >::m_ullInstanceCounter [inline], [static], [protected], [inherited]
Amount of the instances of the module ever created during the program's runtime.
Definition at line 171 of file AEModuleBase.hpp.
const ullint __AEModuleBase< AETimer >::m_ullModuleId [protected], [inherited]
The ID number of the current module.
Definition at line 176 of file AEModuleBase.hpp.
Author
Generated automatically by Doxygen for ArtyK's Console Engine from the source code.